# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: CI
on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Lints
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install `uv`
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Check that the requirements are installable
        run: uv pip install -r pyproject.toml

      - name: Verify licensing metadata
        run: uvx reuse lint

      - name: Verify Python code formatting
        run: uvx black . --check --diff --color

      - name: Lint Python code with flake8
        run: uvx flake8 .
